services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: src/
    ports:
      - "8080:8080"
    environment:
      SPRINT_DATASOURCE_URL: jdbc:postgresql://db:5432/app
      SPRINT_DATASOURCE_USERNAME: app
      SPRINT_DATASOURCE_PASSWORD: app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
  