spring:
  application:
    name: brief20
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update